root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/main.exe ./cmd/api"
bin = "tmp/main.exe"
include_ext = ["go"]
exclude_dir = ["tmp", "vendor"]
delay = 1000 # ms
stop_on_error = true
send_interrupt = true
kill_delay = 500 # ms

[log]
time = true

[screen]
clear_on_rebuild = true

[misc]
clean_on_exit = false  # Set to false for Windows